### ISSUE TITLE
Increase Username Color Lightness for On-Stream Chat Display

### ISSUE THREAD

**Issue by VxJasonxV** [bryanveloso/avalonstar-tv-chat#2]
Certain user's colors don't look particularly good on a black background. Besides the obvious black usernames (used by yours truly and TheHakku), some low Lightness of colors like Dark Purples and various other dark toned names don't blend well on the background.

Raising their chosen color's lightness will preserve the choice of color, but make it more readable on a black background as the on-stream/on-screen chat display uses.

One method of doing so is converting the Hex color to RGB, then to HSL, raising the desired Lightness by 50%, then the updated HSL back to RGB, and then to Hex. This is very possible, but sub-optimal. Shy of making this conversion in the first place, converting it and using HSL in the CSS rules, I also stumbled on http://www.sitepoint.com/javascript-generate-lighter-darker-color/

Passing `0.5` into the ColorLuminance function would be a good place to start, to see how better/worse usernames show up then.

**Comment by bryanveloso** [comment]
Just to add to this, it doesn't seem to work well on blacks. Definitely another TODO item.

**Comment by VxJasonxV** [comment]
I was worried about that, the comments on the SitePoint link I linked to talk about not being able to add color to "true black", I guess I understand why. Sounds like there might have to be an `if color == #000000 ; color = #999999`. That or just bump it to `#000001` and then scale it like the rest.

There's also something about HSL vs HSV here. Something, something... something.
